services:
  api:
    container_name: ecommerce-api
    image: ecommerce-api-dev
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_URI=mongodb://root:root@mongodb:27017
      - OTEL_TRACE_EXPORTER_URL=http://otel-collector:4317

    ports:
      - 3000:3000
    networks:
      - nest
    depends_on:
      - mongodb
    command: npm run start:dev
 
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - .mongodb:/data/db
    ports:
      - 27017:27017
    networks:
      - nest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    command: mongod --auth
  
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "8081:16686"  # Jaeger UI
      - "14268"
      - "14250"
    networks:
      - nest
      
  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "1888:1888"   # pprof extension
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # http gRPC receiver
      - "55679:55679" # zpages extension
    networks:
      - nest
    depends_on:
      - jaeger
    links:
      - jaeger
networks:
  nest:
    driver: bridge